services:
  nextjs:
    develop:
      watch:
        - action: sync
          path: ./nextjs
          target: /app/nextjs/

    build:
      context: ./nextjs
      dockerfile: Dockerfile
    image: avian_local_nextjs
    container_name: avian_local_nextjs
    # env_file:
    # - ./.envs/.local/.nextjs
    ports:
      - "3000:3000"
      - "9230:9230"
      - "9229:9229"
    # volumes:
    #   - ./nextjs/.next/:/app/nextjs/.next/:z
    command: npm run dev
    restart: always
    environment:
      # - VIRTUAL_HOST=localhost
      # - VIRTUAL_PORT=3000
      - "NODE_OPTIONS=--inspect=0.0.0.0:9229"
